/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'trungvo' at '25/08/15 9:03 PM' with Gradle 2.6
 *
 * @author trungvo, @date 25/08/15 9:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
